### ISSUE TITLE
How do i run the app

### ISSUE THREAD

**Issue by VANRYZE** [Jegge/OldMoofKit#1]
I've got some problems with running the program, im not very good with this kind of stuff and i want to try it. Did the installation and added the package to dependency and did the info.plist too. Thats the only 2 things i did and when i tried to run the app it just  gave me "Hello, world!" Is there any video/steps that can show me how i can run the program. Im really sorry i don't understand the Xcode stuff and if theres someone that can help me.

**Comment by Jegge** [comment]
Hi VANRYZE,

the reason it doesn't work is that OldMoofKit is not an app by itself, it's only a library that talks to the VanMoof web api and the bike. The app is the part that you will have to write. To get a minimal working example, you'll have to replace the code that prints "Hello, world!" with the following code (make sure that the username and password matches your VanMoof credentials):

```swift
import OldMoofKit

let bike = try await Bike(username: "Johnny Mnemonic", password: "swordfish") 
try await bike.connect()
try await bike.playSound(.bell)
try await bike.set(lock: .unlocked)
bike.disconnect()
```

This will read the encryption key from the VanMoof web api, connect and unlock the bike and play a bell sound.

Jegge
