### ISSUE TITLE
Is there any detailed step-by-step instruction

### ISSUE THREAD

**Issue by VANRYZE** [Jegge/OldMoofKit#2]
Hi Jegge, 

I saw that you responded on my last issue. I can't seem to replace the "Hello World!" with the code you gave me. It leaves me on (No such modules 'OldMoofKit'. What do i need to do. do i launch xcode as a project (App) or as a workplace. I dont know.. Maybe if theres someone that could help me.
![Screenshot_35](https://github.com/Jegge/OldMoofKit/assets/161765732/67b4bee2-54c7-44fd-bbf5-da120f19fdbd)

**Comment by Jegge** [comment]
Sorry, I cannot help you with that, there are just to many things I do not know about your project and your current programming experience. I starts with the kind of project you are building - is it SwiftUI, UIKit or console based, should it run on macOS, watchOS or iOS? You may find some further information [here](https://www.youtube.com/playlist?list=PLpGHT1n4-mAsxuRxVPv7kj4-dQYoC3VVu) or [here](https://www.youtube.com/watch?v=t_mypMqSXNw) to get you started with SwiftUI on iOS.
