### ISSUE TITLE
Need Help 

### ISSUE THREAD

**Issue by MaDwArLoCk2** [Jegge/OldMoofKit#3]
Hi Jegge, 
Thank you for developing such useful project  for old bikes!  

I have struggled for two days with xCode and definitely my knowledge is not enough to make it work.
It would be very nice if you could give some more tips how to finalize your code.

Actually i need just one option, I would like to switch my S2 to Offroad mode. 
The encryption key I could get with help of another project.

**Comment by Jegge** [comment]
Hi MaDwArLoCk2,

you're welcome! This should do the trick:

```swift
import OldMoofKit

let bike = try await Bike(username: "Johnny Mnemonic", password: "swordfish") 
try await bike.connect()
try await bike.set(region: .offroad)
try await bike.playSound(.bell)
bike.disconnect()
```

I assume that you have created a simple iPhone app that may use Bluetooth Low Energy and added OldMoofKit as a Swift Package. Then you could even call this code in your application(didFinishLaunchingWithOptions:) for testing purposes.

-- DerJegge

**Comment by MaDwArLoCk2** [comment]
Thanks for fast response! 
Honestly i thought that its all in your code already and i can't figure out how to run it. 😅
xCode is something absolutely new for me, so it will take a while till I’ll make a simple working app

**Comment by Jegge** [comment]
That explains the misunderstanding. ^^

If you would send me your Apple ID as a private message (e.g. via [email](mailto:einwegartikel@icloud.com) or [mastodon](https://chaos.social/@Jegge)), I could add you as a beta tester for my complete app that uses this library. That way you could at least experiment with your bike's offroad mode. Beware that it might be illegal to change this setting, depending on where you are living.

-- Jegge

**Comment by MaDwArLoCk2** [comment]
That sounds great! 😊 
I have sent you email. 
Thanks
